# Generated by Django 5.0.6 on 2026-05-04 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_create', 'Création de produit'), ('product_update', 'Modification de produit'), ('product_delete', 'Suppression de produit'), ('stock_in', 'Entrée de stock'), ('stock_out', 'Sortie de stock'), ('stock_adjust', 'Ajustement de stock'), ('stock_return', 'Retour de stock'), ('cart_checkout', 'Validation de panier'), ('revenue_add', 'Ajout de recette'), ('expense_add', 'Ajout de dépense'), ('transaction_delete', 'Suppression de transaction'), ('other', 'Autre')], max_length=30, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activités",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('transaction_type', models.CharField(choices=[('revenue', 'Recette'), ('expense', 'Dépense')], max_length=20, verbose_name='Type')),
                ('category', models.CharField(choices=[('vente', 'Vente de produits'), ('service', 'Prestation de service'), ('achat_stock', 'Achat de stock'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
                'ordering': ['-created_at'],
            },
        ),
    ]
