# Generated by Django 5.0.6 on 2026-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_content',
            field=models.TextField(blank=True, help_text='Description longue affichée sur la page détail. Chaque ligne vide crée un nouveau paragraphe.', verbose_name='Contenu détaillé'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image'),
        ),
    ]
